modelpack/model-spec

- .github/workflows/lint.yml
- .typos.toml
- README.md
- docs/spec.md
Adding a typos linter and fix 2 reports.
> Fix and lint typos

- docs/spec.md
Fixing the spelling of the runtime to become uppercase.
> Fix CRI-O name

- docs/annotations.md
- docs/spec.md
This pull request includes updates to the documentation for better clarity and accuracy, specifically focusing on the model specification and annotations. The most important changes include the removal of certain properties, correction of grammatical errors, and the addition of new media types and artifact types.
Documentation updates:
* [`docs/annotations.md`](diffhunk://#diff-d210c46f7c35fae8f95ec8111564cc357a038b0ec63128f7707f31087a6f7115L38-L39): Removed `org.cnai.model.config` and `org.cnai.model.model` properties to streamline the annotations section.
* [`docs/spec.md`](diffhunk://#diff-d7d183da3129291ef1210410b2898ac6a65a4e4de8ede9775601173545570f57L14-R14): Corrected a grammatical error to ensure proper subject-verb agreement.
Enhancements to model specification:
* …
> feat: add doc and config artifactType for spec

- docs/spec.md
In this PR, I've made the following changes:
1. grammar fixes:
* missing subject
```diff
- If the model has multiple weight files, need to package them in separate layers. But recommended [...]
+ If the model has multiple weight files, they SHOULD be packaged in separate layers.
```
2. removed the "The model specification needs to consider two factors" part.
I don't think design considerations/motivations should be included in the specification document itself (but rather in a separate place such as README.md).
I've transformed this information into a "Use Case" section, similar to the arrangement in the [OCI Distribution Spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#use-cases).
3. reordered the "Workflow" and "Spec Definition" sections:
I think it's better …
> doc: fix some grammar errors and refine some expressions

- docs/spec.md
Changes the specification to adhere to OCI Artifact guidance. Adds a section about the tar layers and reproducibility. Editing changes to clarify. 
fixes #17 and #23
> OCI Artifact changes

- specs-go/v1/mediatype.go
This pull request includes changes to the `specs-go/v1/mediatype.go` file to update and expand the media type constants for model-related artifacts. The most important changes include renaming existing constants for clarity and adding new constants for additional media types.
Renaming for clarity:
* Changed `ArtifactTypeModelManifest` to `MediaTypeModelManifest` to better reflect its purpose.
* Changed `ArtifactTypeModelConfig` to `MediaTypeModelConfig` to better reflect its purpose.
* Changed `ArtifactTypeModelLayer` to `MediaTypeModelLayer` to better reflect its purpose.
* Changed `ArtifactTypeModelLayerGzip` to `MediaTypeModelLayerGzip` to better reflect its purpose.
Adding new media types:
* Added `MediaTypeModelDoc` for model documentation files like `README.md` and `LICENSE`.
* …
> feat: remove artifact types and add media types

- specs-go/v1/config.go
The filed InfoURL is no longer necessary, and seems confusing.
See the [discussion](https://cloud-native.slack.com/archives/C07T0V480LF/p1739257048027399?thread_ts=1739251984.440139&cid=C07T0V480LF).
Signed-off-by: Zhao Chen <zhaochen.zju@gmail.com>
> spec: remove InfoURL in ModelDescriptor

- docs/annotations.md
- docs/spec.md
- specs-go/v1/annotations.go
- specs-go/v1/config.go
- specs-go/v1/mediatype.go
This pull request includes significant updates to the documentation and codebase related to the handling of AI/ML model artifacts. The changes primarily focus on refining the specification, updating media types, and cleaning up deprecated annotations.
* Removed outdated model annotation keys from `docs/annotations.md` to streamline the documentation.
* Added new media types and clarified the use of `artifactType` and `mediaType` in `docs/spec.md`.
* Updated the `+gzip` and `+zstd` media types to include new entries for configuration files in `docs/spec.md`.
* Removed deprecated annotation keys from `specs-go/v1/annotations.go`.
* Renamed `CreateTime` to `CreatedAt` in `specs-go/v1/config.go` to standardize naming conventions.
* Updated media type constants and added new ones for …
> feat: optimize definition of the model spec

- docs/config.md
fix: #27 
Some notes for the reviewer:
1. I haven't imposed any additional restrictions on the `DiffID`, as, according to the [comment](https://github.com/CloudNativeAI/model-spec/issues/22#issuecomment-2582042991), the format doesn't need to be limited to a cryptographic hash. However, the comment might be outdated, and I'm unsure about the current preference.
2. Do we need a more concrete example instead of a mock one? My concern is that, due to point 1, the format of `DiffID` has not been determined yet, which makes it difficult to provide a concrete example at this time.
3. I haven't imposed any additional restrictions on the properties in `config` according to that [the current status is not stable yet](https://cloud-native.slack.com/archives/C07T0V480LF/p1739333803552829?thread_ts=17 …
> add config.md

- .golangci.yml
This pull request includes changes to the `.golangci.yml` configuration file to improve the linter settings and output format.
Configuration improvements:
* Changed the `deadline` parameter to `timeout` under the `run` section to better reflect the intended functionality. (`.golangci.yml`)
Output format enhancement:
* Modified the `output` section to support multiple formats and specified the output path for better clarity and control. (`.golangci.yml`)
> chore: update golangci-lint configuration to remove unsupported properties

- docs/config.md
- docs/spec.md
- specs-go/v1/config.go
This pull request includes changes to update the terminology and format for specifying model parameter sizes across documentation and code. The most important changes include renaming `parameterSize` to `paramSize` and updating corresponding descriptions and examples.
Terminology and format updates:
* [`docs/config.md`](diffhunk://#diff-77b3519370ff48f6caf7c316f0ece966f2f0871c40e9381d451d2c5b1c76b40fL82-R84): Renamed `parameterSize` to `paramSize` and updated the description to reflect the new format, such as "8b", "16b", "32b", etc. [[1]](diffhunk://#diff-77b3519370ff48f6caf7c316f0ece966f2f0871c40e9381d451d2c5b1c76b40fL82-R84) [[2]](diffhunk://#diff-77b3519370ff48f6caf7c316f0ece966f2f0871c40e9381d451d2c5b1c76b40fL129-R129)
* [`specs-go/v1/config.go`](diffhunk://#diff-c2ec7789f5fa73b840512 …
> feat: update parameter size field and documentation

- docs/spec.md
- specs-go/v1/mediatype.go
This commit introduces a `application/vnd.cnai.model.weight.v1.raw` media type. This will be beneficial for large language models, as the model weight files are giant, with individual files reaching up to 10GB and total files nearing 1TB: 
- Eliminates compression and archiving overhead, and accelerates build and start speed
- Reduces storage footprint during archiving and unarchiving
Similar PR in oci-spec: https://github.com/opencontainers/image-spec/pull/1197/files
> feat: add raw media type for model weights files

- docs/annotations.md
- specs-go/v1/annotations.go
This pull request introduces a new annotation key and its associated metadata structure to enhance file layer annotations. The most important changes include the addition of `AnnotationFileMetadata` and the definition of the `FileMetadata` struct to describe file-specific metadata.
* **New annotation key added**: Introduced `org.cnai.model.file.metadata` as a new annotation key to specify file metadata in JSON format. [[1]](diffhunk://#diff-d210c46f7c35fae8f95ec8111564cc357a038b0ec63128f7707f31087a6f7115R10-R41) [[2]](diffhunk://#diff-05a9698dc79be9f08ba5b6fbbaa6bb013a61c3b2db9b5cd1aa570677f7065c0cR19-R51)
* **Definition of `FileMetadata` struct**: Added a `FileMetadata` struct in `specs-go/v1/annotations.go` to define the metadata schema, including file name, permission mode, owner and …
> feat: add the type definition of file metadata annotation

- docs/annotations.md
- specs-go/v1/annotations.go
Hi,
I'm following up to what was presented yesterday call, with https://github.com/CloudNativeAI/model-spec/issues/44, https://github.com/CloudNativeAI/model-spec/issues/49
I'd like to propose a more explicit way to distinguish annotations that are holding a string-based-representation of a known format which is not a pure string scalar, in this case string-based-representation of a JSON object.
This stems from the fact that in OCI spec, Annotations are indeed key-value pair of str-str scalars only.
ref https://github.com/opencontainers/image-spec/blob/64294bd7a2bf2537e1a6a34d687caae70300b0c4/annotations.md?plain=1#L9
I think using a string representation of a structured JSON object in the value is more than fine,
but imho we can make it even more explicit beyond writing in the document: …
> proposal: use `+json` postfix to mark json annotation values

- Makefile
- docs/config.md
- go.mod
- go.sum
- schema/config-schema.json
- schema/config_test.go
- schema/example_test.go
- schema/schema.go
- schema/validator.go
fix: https://github.com/CloudNativeAI/model-spec/issues/46
1. I was unable to find any auto generation involved from json schema to  Go structs or vice versa in image-spec.
2. The logic related to the schema in the `image-spec` repo primarily focuses on (example) validation and Go testing.
This PR attempts to align with that validation and testing logic from image-spec.
To mirror the structure of the `image-spec` repo, I’ve introduced the following Go files with some minor adjustments based on my own understanding:
| `model-spec`               | `image-spec`             | Role                                      |
|----------------------------|---------------------------|-------------------------------------------|
| `schema/schema.go`         | `schema/schema.go`        | Go metadata …
> add json schema for model config

- docs/spec.md
Removes the recommended remarks from `.raw` mediaTypes.
> Remove the recommendation for raw media types

- .github/workflows/stale.yml
This pull request introduces a new GitHub Actions workflow to automate the management of stale issues and pull requests in the repository. The workflow is designed to mark issues and PRs as stale after a period of inactivity and close them if they remain inactive.
* [`.github/workflows/stale.yml`](diffhunk://#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894R1-R31): Added a new workflow named "Close stale issues and PRs" that runs daily and can also be triggered manually. It uses the `actions/stale` action to mark issues and PRs as stale after 40 days of inactivity and close them after an additional 7 days. The workflow includes configurable messages and exemptions for certain labels and milestones.
> chore(.github/workflows): add stale action for workflows

- .github/workflows/pr-labels.yml
This pull request adds a new GitHub Actions workflow to automate labeling for pull requests. The workflow ensures that each pull request has exactly one label from a predefined set of options.
Workflow addition:
* [`.github/workflows/pr-labels.yml`](diffhunk://#diff-cc6cdcc79d6a4cb86fb60d52a99f98fa1241bf2da9b359dd211e4f67d72edd19R1-R20): Introduced a new workflow named "PR Label" that triggers on pull request events (`opened`, `labeled`, `unlabeled`, `synchronize`) and uses the `mheap/github-action-required-labels` action to enforce one label from the following list: `bug`, `enhancement`, `documentation`, `dependencies`.
> chore: add pr-labels actions

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
This pull request adds standardized issue templates to the repository to streamline bug reporting, feature requests, and custom issues. These templates aim to improve the clarity and consistency of issues submitted by contributors.
New issue templates:
* [`.github/ISSUE_TEMPLATE/bug-report.md`](diffhunk://#diff-5870a741e2fa8d0b03a88d7b036d408ee7e6954051fcc5d7978269bf6d1ff242R1-R24): Added a bug report template with sections for describing the issue, expected behavior, reproduction steps, and environment details.
* [`.github/ISSUE_TEMPLATE/feature-request.md`](diffhunk://#diff-e9349fad824a042e877a9a2f15d475a1fb691346b70711c916e495542e2e6e5eR1-R13): Added a feature request template with sections for describing the feature, its use case, and its potential value.
* …
> chore: add issue templates

- docs/config.md
> docs: update precision documentation in model configuration

- code-of-conduct.md
- schema/example_test.go
- schema/schema.go
- schema/validator.go
- specs-go/v1/annotations.go
- specs-go/v1/config.go
- specs-go/v1/mediatype.go
aligns with the name of the project Sandbox
n/a
as description
> docs: align to Sandbox name

- docs/config.md
As #72 has [been merged](https://github.com/modelpack/model-spec/pull/72#event-18582660222), this started to show [broken](https://github.com/modelpack/model-spec/actions/runs/16216825967/job/45788064727) ci/GHA on main. 
This resolves ci/GHA linting and the Documentation for valid JSON.
n/a
see above
> fix(docs): fix JSON in doc and ci/GHA linting

- README.md
Adds a copyright field with the text require by the Linux Foundation. Feel free to move this to another part of the README if needed.
https://github.com/cncf/sandbox/issues/385
This adds the copyright field mentioned on the CNCF onboarding checklist issue above and outlined in the Contribution Agreement instructions doc.
> Add CNCF copyright footer text
